# Generated by Django 2.2.3 on 2019-09-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_one', models.IntegerField(default=0)),
                ('user_two', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('profile_image', models.CharField(max_length=200)),
                ('script', models.CharField(max_length=200)),
                ('date_time', models.CharField(max_length=200)),
                ('non_read_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('real_id', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(default='default_image.PNG', upload_to='')),
                ('profile_image2', models.ImageField(default='default_image.PNG', upload_to='')),
                ('gender', models.CharField(max_length=200)),
                ('like', models.IntegerField(default=0)),
                ('profile_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Last_Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_id', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(default='default_image.PNG', upload_to='')),
                ('profile_image2', models.ImageField(default='default_image.PNG', upload_to='')),
                ('gender', models.CharField(max_length=200)),
                ('profile_text', models.CharField(max_length=200)),
                ('like_check', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(default='default_image.PNG', upload_to='')),
                ('profile_image2', models.ImageField(default='default_image.PNG', upload_to='')),
                ('gender', models.CharField(max_length=200)),
                ('like', models.IntegerField(default=0)),
                ('profile_text', models.CharField(max_length=200)),
            ],
        ),
    ]
