# Generated by Django 2.2.3 on 2019-09-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Bubble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=200)),
                ('user_one', models.IntegerField(default=0)),
                ('user_two', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('profile_image', models.CharField(max_length=200)),
                ('script', models.CharField(max_length=200)),
                ('date_time', models.CharField(max_length=200)),
                ('non_read_check', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='chat_list',
            name='roomName',
            field=models.CharField(default='8240', max_length=200),
        ),
        migrations.AlterField(
            model_name='friends',
            name='profile_image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='friends',
            name='profile_image2',
            field=models.CharField(max_length=200),
        ),
    ]
